version: "3"
services:
  reddit-frontend:
    container_name: reddit-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production
