export const DASH_FETCH_POSTS = "DASH_FETCH_POSTS";
export const MOD_FETCH_COMMUNITIES = "MOD_FETCH_COMMUNITIES";
export const MOD_FETCH_SUBS = "MOD_FETCH_SUBS";
export const INVITE_GET_USERS = "INVITE_GET_USERS";
export const INVITE_FETCH_COMMUNITIES = "INVITE_FETCH_COMMUNITIES";
export const INVITE_FETCH_INVITES = "INVITE_FETCH_INVITES";
export const INVITE_FETCH_RECEIVED_INVITES = "INVITE_FETCH_RECEIVED_INVITES";